/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../Android/NDK/android-ndk-r10d/platforms/android-21/arch-x86/usr/include/jni.h"
/* Header for class com_uugty_uu_util_Md5Util */

#ifndef _Included_com_uugty_uu_util_Md5Util
#define _Included_com_uugty_uu_util_Md5Util
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_uugty_uu_util_Md5Util
 * Method:    getToken
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_uugty_uu_util_Md5Util_getToken
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
